FI.WebAtividadeEntrevista/Controllers/BeneficiarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAtividadeEntrevista.Models;
using FI.AtividadeEntrevista.BLL;
using FI.AtividadeEntrevista.DML;
using Newtonsoft.Json;
using System.IO;
using System.Reflection;

namespace WebAtividadeEntrevista.Controllers
{
    public class BeneficiarioController : Controller
    {
        // GET: Beneficiario
        [HttpGet]
        [Route("Beneficiario/Index/{id}")]
        public ActionResult Index(long id)
        {
            BoBeneficiario bllBen = new BoBeneficiario();
            List<Beneficiario> beneficiarios = bllBen.Listar(id);
            ClienteBeneficiariosModel cliBenModel = new ClienteBeneficiariosModel();
            cliBenModel.Beneficiarios = new List<BeneficiarioModel>();
            BeneficiarioModel ben = null;
            ClienteModel cli = new ClienteModel();
            cli.Id = id;
            cliBenModel.Cliente = cli;

            foreach (Beneficiario beneficiario in beneficiarios)
            {

                ben = new BeneficiarioModel();
                ben.Id = beneficiario.Id;
                ben.Nome = beneficiario.Nome;
                ben.CPF = beneficiario.CPF;
                ben.IdCliente = beneficiario.IdCliente;
                cliBenModel.Beneficiarios.Add(ben);
            }

            return PartialView("Index", cliBenModel);
        }
        
        [HttpPut]
        public JsonResult Alterar(BeneficiarioModel beneficiario)
        {
            try
            {

                if (beneficiario == null)
                {
                    return Json(new { Message = "Dados Inválidos", StatusCode = "400", Records = beneficiario });
                } else
                {
                    beneficiario.CPF = beneficiario?.CPF?.Replace("-", "").Replace(".", "");
                }

                BoBeneficiario bo = new BoBeneficiario();

                if (!this.ModelState.IsValid)
                {
                    List<string> erros = (from item in ModelState.Values
                                          from error in item.Errors
                                          select error.ErrorMessage).ToList();

                    Response.StatusCode = 400;
                    return Json(new { Message = "CPF inválido!", StatusCode = "400" });
                }
                else
                {
                    List<Beneficiario> listBen = bo.Listar(beneficiario.IdCliente);

                    

                    foreach (var item in listBen)
                    {
                        if (item.CPF == beneficiario.CPF && item.Id != beneficiario.Id)
                        {
                            return Json(new { Message = "CPF já cadastrado anteriormente!", StatusCode = "400" });
                        } else if (item.CPF == beneficiario.CPF && item.Nome == beneficiario.Nome)
                        {
                            return Json(new { Message = "Não houveram alterações!", StatusCode = "400" });
                        }
                    }
                   
                    Beneficiario benef = new Beneficiario();
                    benef.CPF = beneficiario.CPF;
                    benef.Id = beneficiario.Id;
                    benef.Nome = beneficiario.Nome;
                    benef.IdCliente = beneficiario.IdCliente;

                    bo.Alterar(benef);
             

                    return Json(new { Message = "Beneficiário alterado com sucesso!", StatusCode = "200" });


                }
            }
            catch (Exception e)
            {
                return Json(new { Message = e.Message, StatusCode = "500" });
            }



        }

        [HttpDelete]
        public JsonResult Excluir(long id)
        {
            try
            {
                BoBeneficiario bo = new BoBeneficiario();



                bo.Excluir(id);


                return Json(new { Message = "Beneficiário excluído com sucesso!", StatusCode = "200" });


            }
            catch (Exception e)
            {
                return Json(new { Message = e.Message, StatusCode = "500" });
            }



        }

        [HttpPost]
        public JsonResult Inserir(BeneficiarioModel beneficiario)
        {
            try
            {

                if (beneficiario == null)
                {
                    return Json(new { Message = "Dados Inválidos", StatusCode = "400", Records = beneficiario });
                }
                else
                {
                    beneficiario.CPF = beneficiario?.CPF?.Replace("-", "").Replace(".", "");
                }

                BoBeneficiario bo = new BoBeneficiario();

                if (!this.ModelState.IsValid)
                {
                    List<string> erros = (from item in ModelState.Values
                                          from error in item.Errors
                                          select error.ErrorMessage).ToList();

                    Response.StatusCode = 400;
                    return Json(new { Message = "CPF inválido!", StatusCode = "400" });
                }
                else
                {
                    List<Beneficiario> listBen = bo.Listar(beneficiario.IdCliente);



                    foreach (var item in listBen)
                    {
                        if (item.CPF == beneficiario.CPF)
                        {
                            return Json(new { Message = "CPF já cadastrado anteriormente!", StatusCode = "400" });
                        }
                    }

                    Beneficiario benef = new Beneficiario();
                    benef.CPF = beneficiario.CPF;
                    benef.Nome = beneficiario.Nome;
                    benef.IdCliente = beneficiario.IdCliente;

                    bo.Inserir(benef);


                    return Json(new { Message = "Beneficiário incluído com sucesso!", StatusCode = "200" });


                }
            }
            catch (Exception e)
            {
                return Json(new { Message = e.Message, StatusCode = "500" });
            }



        }
    }
}

FI.WebAtividadeEntrevista/Controllers/ClienteController.cs
using FI.AtividadeEntrevista.BLL;
using WebAtividadeEntrevista.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FI.AtividadeEntrevista.DML;
using Newtonsoft.Json;

namespace WebAtividadeEntrevista.Controllers
{
    public class ClienteController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Incluir()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Incluir(ClienteModel model)
        {
            BoCliente bo = new BoCliente();
            
            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                
                model.Id = bo.Incluir(new Cliente()
                {                    
                    CEP = model.CEP,
                    CPF = model.CPF,
                    Cidade = model.Cidade,
                    Email = model.Email,
                    Estado = model.Estado,
                    Logradouro = model.Logradouro,
                    Nacionalidade = model.Nacionalidade,
                    Nome = model.Nome,
                    Sobrenome = model.Sobrenome,
                    Telefone = model.Telefone
                });

                if (model.Id == -1)
                    return Json(new { titulo = "CPF já cadastrado!", status = "400", mensagem = "Use outro CPF!" });


                return Json(new { titulo = "Sucesso!", status = "200", mensagem = "Cliente cadastrado com sucesso!" });
            }
        }

        [HttpPut]
        public ActionResult AlterarCliente(ClienteModel model)
        {
            try
            {
                BoCliente bo = new BoCliente();
   
                if (!this.ModelState.IsValid)
                {
                    List<string> erros = (from item in ModelState.Values
                                          from error in item.Errors
                                          select error.ErrorMessage).ToList();
                    var erro = erros.First();
                    Response.StatusCode = 400;
                    var dados = new { titulo = "CPF inválido", status = "400", mensagem = erro };
                    //json = Newtonsoft.Json.JsonConvert.SerializeObject(dados);
                    //Response.ContentType = "application/json";
                    //return Content(json);
                    var json = JsonConvert.SerializeObject(dados);
                    Response.Clear();
                    // Define o Content-Type manualmente
                    Response.ContentType = "application/json"; // Remove charset
                    return Content(json); // Retorna o JSON
                    //var json = JsonConvert.SerializeObject(dados);
                    //var result = new ContentResult
                    //{
                    //    Content = json,
                    //    ContentType = "application/json"
                    //};

                    //return result;
                }
                else
                {
                    model.Id = bo.Alterar(new Cliente()
                    {
                        Id = model.Id,
                        CPF = model.CPF,
                        CEP = model.CEP,
                        Cidade = model.Cidade,
                        Email = model.Email,
                        Estado = model.Estado,
                        Logradouro = model.Logradouro,
                        Nacionalidade = model.Nacionalidade,
                        Nome = model.Nome,
                        Sobrenome = model.Sobrenome,
                        Telefone = model.Telefone
                    });
                    
                    if (model.Id == -1)
                    {
                        Response.StatusCode = 400;
                        var dados1 = new { titulo = "CPF já cadastrado!", status = "400", mensagem = "Use outro CPF!" };
                        //var json1 = Newtonsoft.Json.JsonConvert.SerializeObject(dados1);
                        Response.ContentType = "application/json";
                        var json1 = JsonConvert.SerializeObject(dados1);
                        Response.Clear();
                       // Define o Content-Type manualmente
                        Response.ContentType = "application/json"; // Remove charset
                        return Content(json1); // Retorna o JSON
                        //var json1 = JsonConvert.SerializeObject(dados1);
                        //var result1 = new ContentResult
                        //{
                        //    Content = json1,
                        //    ContentType = "application/json"
                        //};

                        //return result1;
                      //  return Json(dados1, JsonRequestBehavior.AllowGet);
                    }

                    Response.StatusCode = 200;
                    var dados2 = new { titulo = "Sucesso!", status = "200", mensagem = "Cliente alterado com sucesso!" };
                    //var json2 = Newtonsoft.Json.JsonConvert.SerializeObject(dados2);
                    Response.ContentType = "application/json";
                    var json2 = JsonConvert.SerializeObject(dados2);
                    Response.Clear();
                    // Define o Content-Type manualmente
                    Response.ContentType = "application/json"; // Remove charset
                    return Content(json2); // Retorna o JSON
                    //var json2 = JsonConvert.SerializeObject(dados2);
                    //var result2 = new ContentResult
                    //{
                    //    Content = json2,
                    //    ContentType = "application/json"
                    //};
                    //return result2;
                    //return Json(dados2, JsonRequestBehavior.AllowGet);

                }
            
            } catch (Exception e)
            {
                Response.StatusCode = 500;
                var dados3 = new { titulo = "Erro!", status = "500", mensagem = e.Message };
                //var json3 = Newtonsoft.Json.JsonConvert.SerializeObject(dados3);
                Response.ContentType = "application/json";
                var json3 = JsonConvert.SerializeObject(dados3);

                // Define o Content-Type manualmente
                Response.Clear();
                Response.ContentType = "application/json"; // Remove charset
                return Content(json3); // Retorna o JSON
                //var json3 = JsonConvert.SerializeObject(dados3);
                //var result3 = new ContentResult
                //{
                //    Content = json3,
                //    ContentType = "application/json"
                //};
                //return result3;
                //return Json(dados3, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult Alterar(long id)
        {
            BoCliente bo = new BoCliente();
            Cliente cliente = bo.Consultar(id);
            Models.ClienteModel model = null;

            if (cliente != null)
            {
                model = new ClienteModel()
                {
                    Id = cliente.Id,
                    CEP = cliente.CEP,
                    CPF = cliente.CPF,
                    Cidade = cliente.Cidade,
                    Email = cliente.Email,
                    Estado = cliente.Estado,
                    Logradouro = cliente.Logradouro,
                    Nacionalidade = cliente.Nacionalidade,
                    Nome = cliente.Nome,
                    Sobrenome = cliente.Sobrenome,
                    Telefone = cliente.Telefone
                };

            
            }

            return View(model);
        }

        [HttpPost]
        public JsonResult ClienteList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                int qtd = 0;
                string campo = string.Empty;
                string crescente = string.Empty;
                string[] array = jtSorting.Split(' ');

                if (array.Length > 0)
                    campo = array[0];

                if (array.Length > 1)
                    crescente = array[1];

                List<Cliente> clientes = new BoCliente().Pesquisa(jtStartIndex, jtPageSize, campo, crescente.Equals("ASC", StringComparison.InvariantCultureIgnoreCase), out qtd);

                //Return result to jTable
                return Json(new { Result = "OK", Records = clientes, TotalRecordCount = qtd });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

FI.WebAtividadeEntrevista/Views/Cliente/Alterar.cshtml
@model WebAtividadeEntrevista.Models.ClienteModel
@{
    ViewBag.Title = "Alterar Cliente";
}
@section scripts{
    <script>
        var urlAlterar = '@Url.Action("AlterarCliente", "Cliente")';
        var vMethod = "PUT";
        var obj = @Html.Raw(Json.Encode(Model));
        console.log(obj);
        var urlRetorno = '@Url.Action("Index", "Cliente")';
    </script>
    @Scripts.Render("~/bundles/altClientes")
    @Scripts.Render("~/bundles/jquerymask")
    @Scripts.Render("~/bundles/MaskCPF")
    @Scripts.Render("~/bundles/Beneficiarios")
    <script>MascaraCPF("#CPF")</script>

}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.Partial("Forms")

FI.WebAtividadeEntrevista/Views/Cliente/Forms.cshtml
@{
    var vMethod = "GET";
    var alterar = false;
    var incluir = false;

    // Verifique se o Request e o FilePath não são nulos
    if (Request != null && Request.FilePath != null)
    {
        alterar = Request.FilePath.Contains("Alterar");
        incluir = Request.FilePath.Contains("Incluir");

        if (incluir)
        {
            vMethod = "POST";
        }
        else if (alterar)
        {
            vMethod = "PUT";
        }
    }
}

@section scripts{
    <script>
       var urlExclusao = '@Url.Action("Excluir", "Beneficiario", new { id = "" })';
    </script>
    @Scripts.Render("~/bundles/Beneficiarios")
}



<form id="formCadastro" method="@vMethod">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="Nome">Nome:</label>
                <input type="hidden" id="Id" value=0 />
                <input required="required" type="text" class="form-control" id="Nome" name="Nome" placeholder="Ex.: João" maxlength="50" />
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Sobrenome">Sobrenome:</label>
                <input required="required" type="text" class="form-control" id="Sobrenome" name="Sobrenome" placeholder="Ex.: da Silva" maxlength="255" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="CPF">CPF:</label>
                <input required="required" type="text" class="form-control" id="CPF" name="CPF" placeholder="Ex.: xxx.xxx.xxx-xx" maxlength="14" />
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Nacionalidade">Nacionalidade:</label>
                <input required="required" type="text" class="form-control" id="Nacionalidade" name="Nacionalidade" placeholder="Ex.: brasileira" maxlength="50" />
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label for="CEP">CEP:</label>
                <input required="required" type="text" class="form-control" id="CEP" name="CEP" placeholder="Ex.: 01011-100" maxlength="9" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="Estado">Estado:</label>
                <select required="required" id="Estado" class="form-control" name="Estado">
                    <option value="">Selecione</option>
                    <option value="SP">São Paulo</option>
                    <option value="PE">Pernambuco</option>
                </select>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="Cidade">Cidade:</label>
                <input required="required" type="text" class="form-control" id="Cidade" name="Cidade" maxlength="50" placeholder="Ex.: São Paulo" />
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="Logradouro">Logradouro:</label>
                <input required="required" type="text" class="form-control" id="Logradouro" name="Logradouro" placeholder="Ex.: Rua Boa Vista 253" maxlength="500" />
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="Email">E-mail:</label>
                <input required="required" type="text" class="form-control" id="Email" name="Email" placeholder="Ex.: email@email.com" maxlength="2079" />
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Telefone">Telefone:</label>
                <input required="required" type="tel" class="form-control" id="Telefone" name="Telefone" placeholder="Ex.: (11) 2020-3030" maxlength="15" />
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div id="meuModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header" style="display: flex; align-items: center; justify-content: space-between; ">
                    <h5 class="modal-title">Detalhes</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modalBody">
                    <!-- Conteúdo será carregado aqui -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal" onclick="location.reload()">Fechar</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div id="clienteModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div id="clienteHeader" class="modal-header" style="display: flex; align-items: center; justify-content: space-between; ">

                </div>
                <div class="modal-body" id="clienteBody">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal" onclick="location.reload()">Fechar</button>
                </div>
            </div>
        </div>
    </div>

    @if (alterar)
    {
        <div class="row">
            <div class="col-md-6">
                <div class="pull-left">
                    <button type="button" class="btn btn-primary" onclick='ModalBeneficiarios(@Model.Id)'>Beneficiários</button>
                </div>
            </div>
            <div class="col-md-6">
                <div class="pull-right">
                    <button type="submit" class="btn btn-sm btn-success">Salvar</button>
                    @Html.ActionLink("Voltar", "Index", "Cliente", new { }, new { @class = "btn btn-sm btn-danger" })
                </div>
            </div>
        </div>




    }
    else
    {
        <div class="row">
            <div class="col-lg-12">
                <div class="pull-right">
                    <button type="submit" class="btn btn-sm btn-success">Salvar</button>
                    @Html.ActionLink("Voltar", "Index", "Cliente", new { }, new { @class = "btn btn-sm btn-danger" })
                </div>
            </div>
        </div>
    }




</form>

FI.WebAtividadeEntrevista/Views/Cliente/Incluir.cshtml
@{
    ViewBag.Title = "Cadastrar Cliente";
}
@section scripts{
    <script>
        var url = '@Url.Action("Incluir", "Cliente", new { area = "" })';
        var urlRetorno = '@Url.Action("Index", "Cliente", new { area = "" })';
    </script>
    @Scripts.Render("~/bundles/clientes")
    @Scripts.Render("~/bundles/jquerymask")
    @Scripts.Render("~/bundles/MaskCPF")
    <script>MascaraCPF("#CPF")</script>
}

<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.Partial("Forms")

FI.WebAtividadeEntrevista/Views/Cliente/Index.cshtml
@{
    ViewBag.Title = "Clientes";
}
@section scripts{
<script>
    var urlAlteracao = '@Url.Action("Alterar", "Cliente", new { area = "" })';
    var urlClienteList = '@Url.Action("ClienteList", "Cliente", new { area = "" })';

</script>
    @Scripts.Render("~/bundles/listClientes")
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.ActionLink("Novo Cliente", "Incluir", "Cliente", new { }, new { @class= "btn btn-sm btn-primary pull-right" })
<table id="gridClientes" class="table"></table>